<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ резюме из HeadHunter

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import re
import statistics
import plotly.graph_objects as go

# Исследование структуры данных

1. Прочитайте данные с помощью библиотеки Pandas. Совет: перед чтением обратите внимание на разделитель внутри файла.

In [3]:
#ваш код здесь
path = r'C:\Users\dponomareva\Documents\Python Scripts\SF\Head hunter project\data\dst-3.0_16_1_hh_database.csv'
data = pd.read_csv(path, sep=';')
display(data)

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано
...,...,...,...,...,...,...,...,...,...,...,...,...
44739,"Мужчина , 30 лет , родился 17 января 1989",50000 руб.,"Финансист, аналитик, экономист, бухгалтер, мен...","Тверь , готов к переезду (Москва, Химки) , гот...",полная занятость,"полный день, удаленная работа","Опыт работы 7 лет 7 месяцев Финансист, аналит...","ООО ""IAS"" (независимый участник объединения Ru...",Руководитель субгруппы,Высшее образование 2015 Московский гуманитарн...,22.04.2019 12:32,Не указано
44740,"Мужчина , 27 лет , родился 5 марта 1992",39000 руб.,"Системный администратор, IT-специалист","Липецк , готов к переезду , готов к командировкам","проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день, ...","Опыт работы 7 лет Системный администратор, IT...",ИП Пестрецов,Предприниматель,Высшее образование (Бакалавр) 2016 Воронежски...,22.04.2019 13:11,Не указано
44741,"Женщина , 48 лет , родилась 26 декабря 1970",40000 руб.,"Аналитик данных, Математик","Челябинск , готова к переезду , готова к редки...",полная занятость,"полный день, удаленная работа",Опыт работы 21 год 5 месяцев Январь 1998 — по...,"ОАО «ЧМК», Исследовательско-Технологический Це...",Начальник группы аналитики,Высшее образование 2000 Южно-Уральский госуда...,09.04.2019 05:07,Не указано
44742,"Мужчина , 24 года , родился 6 октября 1994",20000 руб.,Контент-менеджер,"Тамбов , не готов к переезду , не готов к кома...","частичная занятость, полная занятость",удаленная работа,Опыт работы 3 года 10 месяцев Контент-менедже...,IQ-Maxima,Менеджер проектов,Высшее образование 2015 Тамбовский государств...,26.04.2019 14:25,Имеется собственный автомобиль
44743,"Мужчина , 38 лет , родился 25 апреля 1980",120000 руб.,Руководитель проекта,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,Опыт работы 15 лет 10 месяцев Руководитель пр...,ПАО ГК ТНС энерго,Руководитель отдела технической поддержки,Высшее образование 1997 Южно-Российский госуд...,05.07.2018 20:15,Не указано

2. Выведите несколько первых (последних) строк таблицы, чтобы убедиться в том, что ваши данные не повреждены. Ознакомьтесь с признаками и их структурой.

In [ ]:
#ваш код здесь
data.head()
data.tail()

3. Выведите основную информацию о числе непустых значений в столбцах и их типах в таблице.

4. Обратите внимание на информацию о числе непустых значений.

In [ ]:
#ваш код здесь
data.info()

5. Выведите основную статистическую информацию о столбцах.

In [ ]:
#ваш код здесьb
data.describe()

In [ ]:
data['Образование и ВУЗ'].nunique()

# Преобразование данных

1. Начнем с простого - с признака **"Образование и ВУЗ"**. Его текущий формат это: **<Уровень образования год выпуска ВУЗ специальность...>**. Например:
* Высшее образование 2016 Московский авиационный институт (национальный исследовательский университет)...
* Неоконченное высшее образование 2000  Балтийская государственная академия рыбопромыслового флота…
Нас будет интересовать только уровень образования.

Создайте с помощью функции-преобразования новый признак **"Образование"**, который должен иметь 4 категории: "высшее", "неоконченное высшее", "среднее специальное" и "среднее".

Выполните преобразование, ответьте на контрольные вопросы и удалите признак "Образование и ВУЗ".

Совет: обратите внимание на структуру текста в столбце **"Образование и ВУЗ"**. Гарантируется, что текущий уровень образования соискателя всегда находится в первых 2ух слов и начинается с заглавной буквы. Воспользуйтесь этим.

*Совет: проверяйте полученные категории, например, с помощью метода unique()*

In [ ]:
#ваш код здесь
data['Образование и ВУЗ'] = data['Образование и ВУЗ'].astype(str)

data['Образование'] = data['Образование и ВУЗ'].apply(lambda x: x.split(' ')[:2])

element_to_remove = 'образование'
def remove_element_from_list(lst):
    lst = [item for item in lst if item != element_to_remove]
    lst = [item.lower() for item in lst]
    lst = ' '.join(lst)
    return lst

data['Образование'] = data['Образование'].apply(lambda x: remove_element_from_list(x))

data.drop('Образование и ВУЗ', axis = 1)

In [ ]:
data.loc[data['Образование'] == 'среднее']

2. Теперь нас интересует столбец **"Пол, возраст"**. Сейчас он представлен в формате **<Пол , возраст , дата рождения >**. Например:
* Мужчина , 39 лет , родился 27 ноября 1979 
* Женщина , 21 год , родилась 13 января 2000
Как вы понимаете, нам необходимо выделить каждый параметр в отдельный столбец.

Создайте два новых признака **"Пол"** и **"Возраст"**. При этом важно учесть:
* Признак пола должен иметь 2 уникальных строковых значения: 'М' - мужчина, 'Ж' - женщина. 
* Признак возраста должен быть представлен целыми числами.

Выполните преобразование, ответьте на контрольные вопросы и удалите признак **"Пол, возраст"** из таблицы.

*Совет: обратите внимание на структуру текста в столбце, в части на то, как разделены параметры пола, возраста и даты рождения между собой - символом ' , '. 
Гарантируется, что структура одинакова для всех строк в таблице. Вы можете воспользоваться этим.*

In [ ]:
#ваш код здесь
data['Пол'] = data['Пол, возраст'].apply(lambda x:x.split(',')[0])

data['Пол'] = data['Пол'].apply(lambda x: x.replace('Мужчина', 'М'))
data['Пол'] = data['Пол'].apply(lambda x: x.replace('Женщина', 'Ж'))

data['Возраст'] = data['Пол, возраст'].apply(lambda x:x.split(',')[1])

def age(x):
    pattern = '[0-9]+'
    matches = re.findall(pattern, x)
    extracted_value = int(matches[0])
    return extracted_value 

data['Возраст'] = data['Возраст'].apply(lambda x: age(x))

data.drop(['Пол, возраст'], axis = 1, inplace = True)

data['Пол'].value_counts(normalize=True)

data['Возраст'].mean()

3. Следующим этапом преобразуем признак **"Опыт работы"**. Его текущий формат - это: **<Опыт работы: n лет m месяцев, периоды работы в различных компаниях…>**. 

Из столбца нам необходимо выделить общий опыт работы соискателя в месяцах, новый признак назовем "Опыт работы (месяц)"

Для начала обсудим условия решения задачи:
* Во-первых, в данном признаке есть пропуски. Условимся, что если мы встречаем пропуск, оставляем его как есть (функция-преобразование возвращает NaN)
* Во-вторых, в данном признаке есть скрытые пропуски. Для некоторых соискателей в столбце стоит значения "Не указано". Их тоже обозначим как NaN (функция-преобразование возвращает NaN)
* В-третьих, нас не интересует информация, которая описывается после указания опыта работы (периоды работы в различных компаниях)
* В-четвертых, у нас есть проблема: опыт работы может быть представлен только в годах или только месяцах. Например, можно встретить следующие варианты:
    * Опыт работы 3 года 2 месяца…
    * Опыт работы 4 года…
    * Опыт работы 11 месяцев…
    * Учитывайте эту особенность в вашем коде

Учитывайте эту особенность в вашем коде

В результате преобразования у вас должен получиться столбец, содержащий информацию о том, сколько месяцев проработал соискатель.
Выполните преобразование, ответьте на контрольные вопросы и удалите столбец **"Опыт работы"** из таблицы.

In [ ]:
#ваш код здесь
def get_experience(arg):
    if arg is np.nan or arg == 'Не указано':
        return None
    year_words=['год', 'года', 'лет']
    month_words=['месяц', 'месяца', 'месяцев']
    arg_splitted = arg.split(' ')[:7]
    years = 0
    months = 0
    for index, item in enumerate(arg_splitted):
        if item in year_words:
            years = int(arg_splitted[index-1])
        if item in month_words:
            months = int(arg_splitted[index-1])
    return int(years*12 + months)

data["Опыт работы (месяц)"] = data["Опыт работы"].apply(lambda x: get_experience(x))

data.drop("Опыт работы", axis = 1)

data["Опыт работы (месяц)"].median()

4. Хорошо идем! Следующий на очереди признак "Город, переезд, командировки". Информация в нем представлена в следующем виде: **<Город , (метро) , готовность к переезду (города для переезда) , готовность к командировкам>**. В скобках указаны необязательные параметры строки. Например, можно встретить следующие варианты:

* Москва , не готов к переезду , готов к командировкам
* Москва , м. Беломорская , не готов к переезду, не готов к командировкам
* Воронеж , готов к переезду (Сочи, Москва, Санкт-Петербург) , готов к командировкам

Создадим отдельные признаки **"Город"**, **"Готовность к переезду"**, **"Готовность к командировкам"**. При этом важно учесть:

* Признак **"Город"** должен содержать только 4 категории: "Москва", "Санкт-Петербург" и "город-миллионник" (их список ниже), остальные обозначьте как "другие".

    Список городов-миллионников:
    
   <code>million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']
    </code>
    Инфорация о метро, рядом с которым проживает соискатель нас не интересует.
* Признак **"Готовность к переезду"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к переезду в признаке "Город, переезд, командировки". Например:
    * … , готов к переезду , …
    * … , не готова к переезду , …
    * … , готова к переезду (Москва, Санкт-Петербург, Ростов-на-Дону)
    * … , хочу переехать (США) , …
    
    Нас интересует только сам факт возможности или желания переезда.
* Признак **"Готовность к командировкам"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к командировкам в признаке "Город, переезд, командировки". Например:
    * … , готов к командировкам , … 
    * … , готова к редким командировкам , …
    * … , не готов к командировкам , …
    
    Нас интересует только сам факт готовности к командировке.
    
    Еще один важный факт: при выгрузки данных у некоторых соискателей "потерялась" информация о готовности к командировкам. Давайте по умолчанию будем считать, что такие соискатели не готовы к командировкам.
    
Выполните преобразования и удалите столбец **"Город, переезд, командировки"** из таблицы.

*Совет: обратите внимание на то, что структура текста может меняться в зависимости от указания ближайшего метро. Учите это, если будете использовать порядок слов в своей программе.*

In [ ]:
#ваш код здесь
#Удаляем текст в скобках
data['Город, переезд, командировки'] = data['Город, переезд, командировки'].apply(lambda x: re.sub("\(.*?\)","", x))

#Разделяем элементы по запятой
data['Город, переезд, командировки'] = data['Город, переезд, командировки'].apply(lambda x: x.split(','))

#Убираем лишние пробелы в первом элементе с названием города
data['Город'] = data['Город, переезд, командировки'].apply(lambda x: x[0].strip())

#Список городов-миллионников
million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']

#Список столиц и городов миллионников для замены остальных громов на «другие»
capitals = ["Москва", "Санкт-Петербург", "город-миллионник"]

#Замена названий городов
data['Город'] = data['Город'].apply(lambda x: x if x not in million_cities else "город-миллионник")
data['Город'] = data['Город'].apply(lambda x: x if x in capitals else "другие")

#Удаление названий городов из столбца
data['Город, переезд, командировки'] = data['Город, переезд, командировки'].apply(lambda x: x[1:])

#Обработка столбца о готовности к переезду
data['Готовность к переезду'] = data['Город, переезд, командировки'].apply(lambda x: x[0].strip().split(' '))
data['Готовность к переезду'] = data['Готовность к переезду'].apply(lambda x: 'False' if x[0] == 'не' else 'True') 

#Обработка столбца о готовности к командировкам
data["Готовность к командировкам"] = data['Город, переезд, командировки'].apply(lambda x: x[1].strip().split(' '))
data["Готовность к командировкам"] = data["Готовность к командировкам"].apply(lambda x: 'False' if x[0] == 'не' else 'True')

#Удаление старого столбца
data.drop("Город, переезд, командировки", axis = 1, inplace = True)

In [ ]:
data['Город'].value_counts(normalize=True)

In [ ]:
mask = data['Готовность к переезду'] == 'True'
mask_2 = data['Готовность к командировкам'] == 'True'
(data.loc[mask & mask_2].shape[0]/data.shape[0])*100

5. Рассмотрим поближе признаки **"Занятость"** и **"График"**. Сейчас признаки представляют собой набор категорий желаемой занятости (полная занятость, частичная занятость, проектная работа, волонтерство, стажировка) и желаемого графика работы (полный день, сменный график, гибкий график, удаленная работа, вахтовый метод).
На сайте hh.ru соискатель может указывать различные комбинации данных категорий, например:
* полная занятость, частичная занятость
* частичная занятость, проектная работа, волонтерство
* полный день, удаленная работа
* вахтовый метод, гибкий график, удаленная работа, полная занятость

Такой вариант признаков имеет множество различных комбинаций, а значит множество уникальных значений, что мешает анализу. Нужно это исправить!

Давайте создадим признаки-мигалки для каждой категории: если категория присутствует в списке желаемых соискателем, то в столбце на месте строки рассматриваемого соискателя ставится True, иначе - False.

Такой метод преобразования категориальных признаков называется One Hot Encoding и его схема представлена на рисунке ниже:
<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/ohe.jpg>
Выполните данное преобразование для признаков "Занятость" и "График", ответьте на контрольные вопросы, после чего удалите их из таблицы

In [ ]:
#ваш код здесь
#Список возможных занятостей
occupation = ['полная занятость', 'частичная занятость', 'частичная занятость', 'проектная работа', 'волонтерство']

#Создание новых пустых столбцов по занятостям
for col_name in occupation:
    data[col_name] = pd.Series(dtype=object)
    
#One hot encoder преобразование
for word in occupation:
    mask = data['Занятость'].str.contains(word)
    data.loc[mask, word] = 'True'
    data[word].fillna('False', inplace = True)
    
#Список возможных графиков
schedule = ['полный день', 'удаленная работа', 'вахтовый метод', 'гибкий график', 'удаленная работа', 'полная занятость']

#Создание новых столбцов по графикам
for col_name in schedule:
    data[col_name] = pd.Series(dtype=object)
    
#One hot encoder преобразование
for word in schedule:
    mask = data["График"].str.contains(word)
    data.loc[mask, word] = 'True'
    data[word].fillna('False', inplace = True)

In [ ]:
mask = data['проектная работа'] == 'True'
mask_2 = data['волонтерство'] == 'True'
data.loc[mask & mask_2].shape[0]

In [ ]:
mask = data['вахтовый метод'] == 'True'
mask_2 = data['гибкий график'] == 'True'
data.loc[mask & mask_2].shape[0]

In [ ]:
#Удаление старого столбца
data.drop('Занятость', axis = 1, inplace = True)

In [ ]:
#Удаление старого столбца
data.drop("График", axis = 1, inplace = True)

6. (2 балла) Наконец, мы добрались до самого главного и самого важного - признака заработной платы **"ЗП"**. 
В чем наша беда? В том, что помимо желаемой заработной платы соискатель указывает валюту, в которой он бы хотел ее получать, например:
* 30000 руб.
* 50000 грн.
* 550 USD

Нам бы хотелось видеть заработную плату в единой валюте, например, в рублях. Возникает вопрос, а где взять курс валют по отношению к рублю?

На самом деле язык Python имеет в арсенале огромное количество возможностей получения данной информации, от обращения к API Центробанка, до использования специальных библиотек, например pycbrf. Однако, это не тема нашего проекта.

Поэтому мы пойдем в лоб: обратимся к специальным интернет-ресурсам для получения данных о курсе в виде текстовых файлов. Например, MDF.RU, данный ресурс позволяет удобно экспортировать данные о курсах различных валют и акций за указанные периоды в виде csv файлов. Мы уже сделали выгрузку курсов валют, которые встречаются в наших данных за период с 29.12.2017 по 05.12.2019. Скачать ее вы можете **на платформе**

Создайте новый DataFrame из полученного файла. В полученной таблице нас будут интересовать столбцы:
* "currency" - наименование валюты в ISO кодировке,
* "date" - дата, 
* "proportion" - пропорция, 
* "close" - цена закрытия (последний зафиксированный курс валюты на указанный день).


Перед вами таблица соответствия наименований иностранных валют в наших данных и их общепринятых сокращений, которые представлены в нашем файле с курсами валют. Пропорция - это число, за сколько единиц валюты указан курс в таблице с курсами. Например, для казахстанского тенге курс на 20.08.2019 составляет 17.197 руб. за 100 тенге, тогда итоговый курс равен - 17.197 / 100 = 0.17197 руб за 1 тенге.
Воспользуйтесь этой информацией в ваших преобразованиях.

<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/table.jpg>


Осталось только понять, откуда брать дату, по которой определяется курс? А вот же она - в признаке **"Обновление резюме"**, в нем содержится дата и время, когда соискатель выложил текущий вариант своего резюме. Нас интересует только дата, по ней бы и будем сопоставлять курсы валют.

Теперь у нас есть вся необходимая информация для того, чтобы создать признак "ЗП (руб)" - заработная плата в рублях.

После ответа на контрольные вопросы удалите исходный столбец заработной платы "ЗП" и все промежуточные столбцы, если вы их создавали.

Итак, давайте обсудим возможный алгоритм преобразования: 
1. Перевести признак "Обновление резюме" из таблицы с резюме в формат datetime и достать из него дату. В тот же формат привести признак "date" из таблицы с валютами.
2. Выделить из столбца "ЗП" сумму желаемой заработной платы и наименование валюты, в которой она исчисляется. Наименование валюты перевести в стандарт ISO согласно с таблицей выше.
3. Присоединить к таблице с резюме таблицу с курсами по столбцам с датой и названием валюты (подумайте, какой тип объединения надо выбрать, чтобы в таблице с резюме сохранились данные о заработной плате, изначально представленной в рублях). Значение close для рубля заполнить единицей 1 (курс рубля самого к себе)
4. Умножить сумму желаемой заработной платы на присоединенный курс валюты (close) и разделить на пропорцию (обратите внимание на пропуски после объединения в этих столбцах), результат занести в новый столбец "ЗП (руб)".

In [ ]:
#ваш код здесь
#Загрузка валют
exchange = pd.read_csv('data/ExchangeRates.csv', sep=',')

#Преобразование формата даты
exchange['date']= pd.to_datetime(exchange['date'])
data['Обновление резюме'] = pd.to_datetime(data['Обновление резюме']).dt.date

#Выделение указанной валюты зарплаты
data['ЗП'] = data['ЗП'].apply(lambda x: x.split(' '))
data['currency'] = np.nan
data['currency'] = data['ЗП'].apply(lambda x: x[1])

#Создание словаря с данными валют
curenc_dict = {'грн.': ['UAH', 10], 'руб.': ['RUB', 1], 'бел.руб.': ['BYN', 1], 'KZT': ['KZT', 100], 'EUR': ['EUR', 1], 'USD': ['USD', 1], 'сум': ['UZS', 10000], 'KGS': ['KGS', 10], 'AZN': ['AZN', 1]}

#Преобразование наименований валют согласно словарю
data['currency'] = data['currency'].apply(lambda x: curenc_dict[x][0])

#Подготовка таблиц и их объединение
data.rename(columns={'Обновление резюме': 'date'}, inplace=True)
data['date']= pd.to_datetime(data['date'])
exchange.drop(columns=['per', 'time', 'vol'], axis=1, inplace=True)
data = data.join(
    exchange.set_index(['date', 'currency']),
    on=['date', 'currency'],
    how='left'
)

#Коэффициенты для рубля
mask = data['currency'] == 'RUB'
data.loc[mask, 'close'] = 1
data.loc[mask, 'proportion'] = 1

#Создание нового столбца с зарплатой в рублях
data['ЗП (руб)'] = data['ЗП'].apply(lambda x: int(x[0]))
data['ЗП (руб)'] = data['ЗП (руб)']*data['close']/data['proportion']
data.drop(columns=['ЗП', 'currency', 'close', 'proportion'], axis=1, inplace=True)
data['ЗП (руб)'].median()

# Исследование зависимостей в данных

1. Постройте распределение признака **"Возраст"**. Опишите распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится возраст большинства соискателей? Есть ли аномалии для признака возраста, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
# Create a histogram using Plotly Express
fig = px.histogram(data['Возраст'], nbins=10, marginal='box')

# Update layout for labels and title
fig.update_layout(
    title='Histogram',
    xaxis_title='Возраст',
    yaxis_title='Amount'
)

# Show the plot
fig.show()

In [ ]:
statistics.mode(data['Возраст'])

ваши выводы по графику здесь<br>
<br>
Больше всего резюме от людей в возрасте 20-39 лет

2. Постройте распределение признака **"Опыт работы (месяц)"**. Опишите данное распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится опыт работы большинства соискателей? Есть ли аномалии для признака опыта работы, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
# ваш код здесь
# Create a histogram using Plotly Express
fig = px.histogram(data['Опыт работы (месяц)'], nbins=10, marginal='box')

# Update layout for labels and title
fig.update_layout(
    title='Histogram',
    xaxis_title='Опыт работы (месяц)',
    yaxis_title='Amount'
)

# Show the plot
fig.show()

In [ ]:
statistics.mode(data['Опыт работы (месяц)'])

ваши выводы здесь<br>
<br>
Мода составляет 81 месяц,<br>
<br>
Опыт работы представлен у соискателей между одним месяцем и 1188 месяцами,<br>
<br>
Большинство соискателей имеют опыт работы 57-154 месяцев,<br>
<br>
Аномалиями можно назвать значения более 300 месяцев опыта работы

3. Постройте распределение признака **"ЗП (руб)"**. Опишите данное распределение, отвечая на следующие вопросы: каковы предельные значения признака, в каком примерном интервале находится заработная плата большинства соискателей? Есть ли аномалии для признака возраста? Обратите внимание на гигантские размеры желаемой заработной платы.
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
fig = px.histogram(
    data_frame=data,
    x='ЗП (руб)',
    title='Распределение желаемой з/п соискателей',
    histnorm='percent',
    width=500,
    marginal='box'
)
fig.show()

ваши выводы здесь<br>
<br>
Уровень зарплат варьируется в пределах между одним рублем и 24.3 млн рублей,<br>
<br>
Наиболее частые зарплаты находятся в диапазоне от 37 тысяч до 95 тысяч рублей,<br>
<br>
Аномалиями можно считать значения выше 1 млн рублей

4. Постройте диаграмму, которая показывает зависимость **медианной** желаемой заработной платы (**"ЗП (руб)"**) от уровня образования (**"Образование"**). Используйте для диаграммы данные о резюме, где желаемая заработная плата меньше 1 млн рублей.
*Сделайте выводы по представленной диаграмме: для каких уровней образования наблюдаются наибольшие и наименьшие уровни желаемой заработной платы? Как вы считаете, важен ли признак уровня образования при прогнозировании заработной платы?*

In [ ]:
# ваш код здесь
mask = data['ЗП (руб)'] < 1000000
data_education = data.loc[mask].groupby('Образование', as_index=False)['ЗП (руб)'].median()

data_education

fig = px.bar(
    data_frame=data_education,
    x='Образование',
    y = 'ЗП (руб)',
    title='Распределение желаемой з/п соискателей',
    width=500,
)
fig.show()

ваши выводы здесь <br>
<br>
Выше всего на рынке труда ценятся люди с высшим образованием, и ниже всего люди средним и средним специальным образованиями.<br>
<br>
У людей без опыта работы или с минимальным опытом работы, уровень образования составляет важную роль при прогнозировании заработной платы. С увеличением рабочего стажа, составляющая уровня образования в прогнозируемой заработной платы уменьшается.

5. Постройте диаграмму, которая показывает распределение желаемой заработной платы (**"ЗП (руб)"**) в зависимости от города (**"Город"**). Используйте для диаграммы данные о резюме, где желая заработная плата меньше 1 млн рублей.
*Сделайте выводы по полученной диаграмме: как соотносятся медианные уровни желаемой заработной платы и их размах в городах? Как вы считаете, важен ли признак города при прогнозировании заработной платы?*

In [ ]:
# ваш код здесь
mask = data['ЗП (руб)'] < 1000000
data_education = data.loc[mask].groupby('Город', as_index=False)['ЗП (руб)'].median()

data_education

fig = px.bar(
    data_frame=data_education,
    x='Город',
    y = 'ЗП (руб)',
    title='Распределение желаемой з/п соискателей',
    width=500,
    color_discrete_sequence=['red']
)
fig.show()

In [ ]:
box_data = data[data['ЗП (руб)']<1e6]
fig = px.box(
    data_frame=box_data,
    x='Город',
    y='ЗП (руб)',
    color='Город',
    title='Распределение з/п по городам'
)
fig.show()

ваши выводы здесь <br>
<br>
Для всех городов медианная заработная плата находится в пределах размахов желаемых заработных плат. Наибольший размах по желаемым заработным платам принадлежит Москве.<br>
<br>
Города миллионники имеют одинаковое медианное значение вместе с другими городами.<br>
<br>
Город проживания влияет на прогнозирование заработной платы, так как стоимость проживания в каждом городе разная

6. Постройте **многоуровневую столбчатую диаграмму**, которая показывает зависимость медианной заработной платы (**"ЗП (руб)"**) от признаков **"Готовность к переезду"** и **"Готовность к командировкам"**. Проанализируйте график, сравнив уровень заработной платы в категориях.

In [ ]:
# ваш код здесь
data_education = data.groupby(['Готовность к переезду', 'Готовность к командировкам'], as_index=False)['ЗП (руб)'].median()
data_education

bar_data = data.groupby(
    ['Готовность к командировкам', 'Готовность к переезду'],
    as_index=False
)['ЗП (руб)'].median()
fig = px.bar(
    data_frame=bar_data,
    y='Готовность к переезду',
    x='ЗП (руб)',
    barmode="group",
    color='Готовность к командировкам',
    orientation='h',
    title='Медианная з/п по готовности к командировкам/переезду'
)
fig.show()

ваши выводы здесь<br>
<br>
Самое высокое медианное значение желаемой заработной платы у людей готовых к переезду, но не готовых к командировкам. Судя по медианному значение, речь идет о переезде в Москву.<br>
<br>
Самое низкое значение заработной платы у людей не готовых к переезду и не готовых к командировкам

7. Постройте сводную таблицу, иллюстрирующую зависимость **медианной** желаемой заработной платы от возраста (**"Возраст"**) и образования (**"Образование"**). На полученной сводной таблице постройте **тепловую карту**. Проанализируйте тепловую карту, сравнив показатели внутри групп.

In [ ]:
pivot=data.pivot_table(
    values='ЗП (руб)',
    columns='Возраст',
    index='Образование',
    aggfunc='median',
    fill_value=0
)
pivot

In [ ]:
# ваш код здесь
fig, axes = plt.subplots(figsize=(12, 6))
heatmap = sns.heatmap(data=pivot, ax=axes, cmap='YlGnBu')

ваши выводы здесь
В зависимости от возраста, люди со средним образование быстрее достигают максимальной зарплаты

8. Постройте **диаграмму рассеяния**, показывающую зависимость опыта работы (**"Опыт работы (месяц)"**) от возраста (**"Возраст"**). Опыт работы переведите из месяцев в года, чтобы признаки были в едином масштабе. Постройте на графике дополнительно прямую, проходящую через точки (0, 0) и (100, 100). Данная прямая соответствует значениям, когда опыт работы равен возрасту человека. Точки, лежащие на этой прямой и выше нее - аномалии в наших данных (опыт работы больше либо равен возрасту соискателя)

In [ ]:
# ваш код здесь
data['Опыт работы (года)'] = data['Опыт работы (месяц)'].apply(lambda x: x/12)

fig = px.scatter(
    data_frame=data,
    x='Возраст',
    y='Опыт работы (года)',
    width=1000,
    height=1000,
    title='Зависимость опыта работы от возраста'
)

reference_line = go.Scatter(x=[0, 100],
                            y=[0, 100],
                            mode="lines",
                            line=go.scatter.Line(color="red"),
                            showlegend=False)

fig.add_trace(reference_line)

fig.update_layout(
    xaxis_title='Возраст, лет',
    yaxis_title='Опыт работы (года)'
)
fig.show()

ваши выводы здесь <br>
<br>
С увеличение возраста опыт работы растет, и это логично.<br>
<br>
В основном люди начинают работать с 18-33 лет.<br>
<br>
Основная масса людей прекращает работать между 55-60 годами

**Дополнительные баллы**

Для получения 2 дополнительных баллов по разведывательному анализу постройте еще два любых содержательных графика или диаграммы, которые помогут проиллюстрировать влияние признаков/взаимосвязь между признаками/распределения признаков. Приведите выводы по ним. Желательно, чтобы в анализе участвовали признаки, которые мы создавали ранее в разделе "Преобразование данных".

In [ ]:
# ваш код здесь

data.keys()

fig = px.scatter(
    data_frame=data,
    x='Возраст',
    y='Опыт работы (года)',
    color='Пол',
    width=1000,
    height=1000,
    title='Зависимость опыта работы от возраста для мужчин и женщин'
)

reference_line = go.Scatter(x=[0, 100],
                            y=[0, 100],
                            mode="lines",
                            line=go.scatter.Line(color="red"),
                            showlegend=False)

fig.add_trace(reference_line)

fig.update_layout(
    xaxis_title='Возраст, лет',
    yaxis_title='Опыт работы (года)'
)
fig.show()

ваши выводы здесь<br>
<br>
Женщины начинают работать на два-три года позже, чем мужчины. <br>
<br>
Большинство женщин оставляет работу до 50-ти лет.<br>

# Очистка данных

1. Начнем с дубликатов в наших данных. Найдите **полные дубликаты** в таблице с резюме и удалите их.

In [ ]:
# ваш код здесь
duplicates = data[data.duplicated(subset=data.columns)]
data = data.drop_duplicates()
print(duplicates.shape[0])

2. Займемся пропусками. Выведите информацию **о числе пропусков** в столбцах.

In [ ]:
# ваш код здесь
data.info()

null_data = data.isnull().sum()
display(null_data[null_data > 0])

3. Итак, у нас есть пропуски в 3ех столбцах: **"Опыт работы (месяц)"**, **"Последнее/нынешнее место работы"**, **"Последняя/нынешняя должность"**. Поступим следующим образом: удалите строки, где есть пропуск в столбцах с местом работы и должностью. Пропуски в столбце с опытом работы заполните **медианным** значением.

In [ ]:
# ваш код здесь
data = data.dropna(subset=['Последнее/нынешнее место работы', 'Последняя/нынешняя должность'])

data['Опыт работы (месяц)'] = data['Опыт работы (месяц)'].fillna(data['Опыт работы (месяц)'].median())

In [ ]:
round(data['Опыт работы (месяц)'].mean())

4. Мы добрались до ликвидации выбросов. Сначала очистим данные вручную. Удалите резюме, в которых указана заработная плата либо выше 1 млн. рублей, либо ниже 1 тыс. рублей.

In [ ]:
data

In [ ]:
# ваш код здесь
outliers = data[(data['ЗП (руб)'] > 1e6) | (data['ЗП (руб)'] < 1e3)]
data = data.drop(outliers.index)
print(outliers.shape[0])

5. В процессе разведывательного анализа мы обнаружили резюме, в которых **опыт работы в годах превышал возраст соискателя**. Найдите такие резюме и удалите их из данных

In [ ]:
# ваш код здесь
outliers = data[(data['Возраст'] < data['Опыт работы (года)'])]
data = data.drop(outliers.index)
print(outliers.shape[0])

6. В результате анализа мы обнаружили потенциальные выбросы в признаке **"Возраст"**. Это оказались резюме людей чересчур преклонного возраста для поиска работы. Попробуйте построить распределение признака в **логарифмическом масштабе**. Добавьте к графику линии, отображающие **среднее и границы интервала метода трех сигм**. Напомним, сделать это можно с помощью метода axvline. Например, для построение линии среднего будет иметь вид:

`histplot.axvline(log_age.mean(), color='k', lw=2)`

В какую сторону асимметрично логарифмическое распределение? Напишите об этом в комментарии к графику.
Найдите выбросы с помощью метода z-отклонения и удалите их из данных, используйте логарифмический масштаб. Давайте сделаем послабление на **1 сигму** (возьмите 4 сигмы) в **правую сторону**.

Выведите таблицу с полученными выбросами и оцените, с каким возрастом соискатели попадают под категорию выбросов?

In [ ]:
# ваш код здесь
fig, ax = plt.subplots(1, 1, figsize=(8, 4))
log_age = np.log(data['Возраст'] + 1)
histplot = sns.histplot(log_age, bins=30, ax=ax)
histplot.axvline(log_age.mean(), color='k', lw=2)
histplot.axvline(log_age.mean()+ 4 *log_age.std(), color='k', ls='--', lw=2)
histplot.axvline(log_age.mean()- 3 *log_age.std(), color='k', ls='--', lw=2)
histplot.set_title('Распределение возраста')

In [ ]:
def outliers_z_score_mod(data, feature, left=3, right=3, bias=1, log_scale=False):
    if log_scale:
        x = np.log(data[feature]+bias)
    else:
        x = data[feature]
    
    mu = x.mean() 
    sigma = x.std() 
    
    lower_bound = mu - left * sigma 
    upper_bound = mu + right * sigma 
    outliers = data[(x < lower_bound) | (x > upper_bound)]
    cleaned = data[(x > lower_bound) & (x < upper_bound)]
    
    return outliers, cleaned

outliers, cleaned = outliers_z_score_mod(data, 'Возраст', 3, 4, bias=0, log_scale=True)

In [ ]:
outliers

ваш коммментарий здесь